server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enable: true  # Habilita el descubrimiento dinámico de rutas basadas en los servicios registrados en Eureka.

      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/category/**
            - Path=/product/**

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

        - id: ms-envio-service
          uri: lb://ms-envio-service
          predicates:
            - Path=/envio/**

        - id: ms-proveedor-service
          uri: lb://ms-proveedor-service
          predicates:
            - Path=/proveedor/**

        - id: ms-pedido-service
          uri: lb://ms-pedido-service
          predicates:
            - Path=/pedido/**

        - id: ms-inventario-service
          uri: lb://ms-inventario-service
          predicates:
            - Path=/inventario/**

        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/cliente/**

        - id: ms-pago-service
          uri: lb://ms-pago-service
          predicates:
            - Path=/pago/**
